### ISSUE TITLE
Error deploy Rails

### ISSUE THREAD

**Issue by KAIOAVILA** [GoogleCloudPlatform/appengine-ruby#25]
Hi, I'm with problem for deploy rails in appengine.

It is presenting current error:

```
Step #1: success Saved lockfile.
Step #1: Done in 0.07s.
Step #1: /app/vendor/bundle/ruby/2.4.0/gems/google-cloud-logging-1.6.0/lib/google/cloud/logging/async_writer.rb:423:in `publish_batch_async': uninitialized constant Concurrent::Promises (NameError)
Step #1: 	from /app/vendor/bundle/ruby/2.4.0/gems/google-cloud-logging-1.6.0/lib/google/cloud/logging/async_writer.rb:396:in `publish_batch!'
Step #1: 	from /app/vendor/bundle/ruby/2.4.0/gems/google-cloud-logging-1.6.0/lib/google/cloud/logging/async_writer.rb:212:in `block in stop'
Step #1: 	from /opt/rbenv/versions/2.4.2/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
Step #1: 	from /app/vendor/bundle/ruby/2.4.0/gems/google-cloud-logging-1.6.0/lib/google/cloud/logging/async_writer.rb:208:in `stop'
Step #1: 	from /app/vendor/bundle/ruby/2.4.0/gems/google-cloud-logging-1.6.0/lib/google/cloud/logging/async_writer.rb:86:in `block in initialize'
Step #1: Removing intermediate container b05e3c93fc9f
Step #1:  ---> 53f45fb74bb9

```

**Comment by dazuma** [comment]
Try updating your bundle. (The latest google-cloud-logging version is 1.6.4.)
